services:
  php-apache-environment:
    container_name: php-apache
    build: ./php
    image: php:8.0-apache
    volumes:
      - ${FILE_SOURCE}:/var/www/
    ports:
      - 8000:80
  db:
    container_name: db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      MYSQL_USER: mysql
      MYSQL_PASSWORD: root
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db